// fxdom 0.0.16
import qs from './qs.js';
import qsa from './qsa.js';
import find from './find.js';
import findAll from './findAll.js';
import children from './children.js';
import closest from './closest.js';
import is from './is.js';
import prevAll from './prevAll.js';
import nextAll from './nextAll.js';
import prev from './prev.js';
import next from './next.js';
import contains from './contains.js';
import remove from './remove.js';
import els from './els.js';
import el from './el.js';
import appendTo from './appendTo.js';
import prepend from './prepend.js';
import before from './before.js';
import after from './after.js';
import text from './text.js';
import setText from './setText.js';
import html from './html.js';
import setHTML from './setHTML.js';
import outerHTML from './outerHTML.js';
import setOuterHTML from './setOuterHTML.js';
import val from './val.js';
import setVal from './setVal.js';
import attr from './attr.js';
import setAttr from './setAttr.js';
import removeAttr from './removeAttr.js';
import addClass from './addClass.js';
import removeClass from './removeClass.js';
import toggleClass from './toggleClass.js';
import scrollTop from './scrollTop.js';
import scrollLeft from './scrollLeft.js';
import setScrollTop from './setScrollTop.js';
import setScrollLeft from './setScrollLeft.js';
import offset from './offset.js';
import on from './on.js';
import off from './off.js';
import delegate from './delegate.js';
import trigger from './trigger.js';
import focus from './focus.js';
import blur from './blur.js';
import param from './param.js';
import get from './get.js';
import post from './post.js';
import put from './put.js';
import del from './del.js';
import postForm from './postForm.js';
import setData from './setData.js';
import data from './data.js';
import css from './css.js';
import setCss from './setCss.js';
import width from './width.js';
import innerWidth from './innerWidth.js';
import outerWidth from './outerWidth.js';
import height from './height.js';
import innerHeight from './innerHeight.js';
import outerHeight from './outerHeight.js';
import show from './show.js';
import hide from './hide.js';
import toggle from './toggle.js';

window.$ = {};

$.qs = qs;
$.qsa = qsa;
$.find = find;
$.findAll = findAll;
$.children = children;
$.closest = closest;
$.is = is;
$.prevAll = prevAll;
$.nextAll = nextAll;
$.prev = prev;
$.next = next;
$.contains = contains;
$.remove = remove;
$.els = els;
$.el = el;
$.append = append;
$.prepend = prepend;
$.before = before;
$.after = after;
$.text = text;
$.setText = $.set_text = setText;
$.html = html;
$.setHTML = $.set_html = setHTML;
$.outerHTML = outerHTML;
$.setOuterHTML = $.set_outer_html = setOuterHTML;
$.val = val;
$.setVal = $.set_val = setVal;
$.attr = attr;
$.setAttr = $.set_attr = setAttr;
$.removeAttr = $.remove_attr = removeAttr;
$.addClass = $.add_class = addClass;
$.removeClass = $.remove_class = removeClass;
$.toggleClass = $.toggle_class = toggleClass;
$.scrollTop = $.scroll_top = scrollTop;
$.scrollLeft = $.scroll_left = scrollLeft;
$.setScrollTop = $.set_scroll_top = setScrollTop;
$.setScrollLeft = $.set_scroll_left = setScrollLeft;
$.offset = offset;
$.on = on;
$.off = off;
$.delegate = delegate;
$.trigger = trigger;
$.focus = focus;
$.blur = blur;
$.param = param;
$.get = get;
$.post = post;
$.put = put;
$.del = del;
$.postForm = $.post_form = postForm;
$.setData = $.set_data = setData;
$.data = data;
$.css = css;
$.setCss = $.set_css = setCss;
$.width = width;
$.innerWidth = $.inner_width = innerWidth;
$.outerWidth = $.outer_width = outerWidth;
$.height = height;
$.innerHeight = $.inner_height = innerHeight;
$.outerHeight = $.outer_height = outerHeight;
$.show = show;
$.hide = hide;
$.toggle = toggle;
